### ISSUE TITLE
能不能添加一个api，方便测试调试信息

### ISSUE THREAD

**Issue by indiboy** [xxf098/LiteSpeedTest#13]
如 api：http://127.0.0.1:10888/api
请求参数->返回信息。

**Comment by xxf098** [comment]
能具体点吗？
从api输入节点，配置信息，然后同步返回延迟，速度信息？

**Comment by indiboy** [comment]
是的，是这个意思，传入节点，返回ping值，速度，节点类型 等等必要信息
可以单独测试，比如说只测试ping，只测速
可以一次传入一个节点就可以了

**Comment by indiboy** [comment]
比如说：http://127.0.0.1:10888/api/ 请求参数 【jiedian=节点地址】
返会
` {
code:0,
type:ssr,
ping:2,
speed:3
}`

**Comment by xxf098** [comment]
可以使用grpc
