### ISSUE TITLE
About speed measurement data export

### ISSUE THREAD

**Issue by a2470982985** [xxf098/LiteSpeedTest#17]
Hello
Is there a way to output the speed measurement results to json to facilitate obtaining the optimal data results,
like this
{
        "id": 111,
         "group": "1",
         "remarks": "TG Channel: @kxswa | China",
         "protocol": "vmess",
         "ping": "522",
         "avg_speed": 10744570,
         "max_speed": 19183743,
         "isok": true,
         "traffic": 67604836,
         "Link": "vmess://OiIifzasFfasQ=="
}
thanks

**Comment by a2470982985** [comment]
Because I am not familiar with the go language, I want to call it through java or python🤦‍♂️

**Comment by xxf098** [comment]
grpc python example :
[liteclientpy](https://github.com/xxf098/LiteSpeedTest/tree/develop/api/rpc/liteclientpy)
