### ISSUE TITLE
mac 版没有生成 out.json文件

### ISSUE THREAD

**Issue by ZhouG2** [xxf098/LiteSpeedTest#21]
lite-darwin-amd64
lite-linux-amd64
  if sys.platform.startswith("darwin"):
        args = ['./lite-darwin-amd64', '--config', './config.json', '--test', 'Eternity']
    elif os.name  == 'posix':
        args = ['./lite-linux-amd64', '--config', './config.json', '--test', 'Eternity']
相同的版本，相同的命令，mac版没有输出out.jso

**Comment by xxf098** [comment]
用下面的配置在macos上测试了，可以生成`out.png`
```bash
echo '{"group": "cronjob", "speedtestMode": "all", "pingMethod": "googleping", "sortMethod": "rspeed", "concurrency": 2, "testMode": 2, "subscription": "https://raw.githubusercontent.com/freefq/free/master/v2", "timeout": 16, "language": "en", "fontSize": 24, "theme": "rainbow", "generatePicMode": 1}' > config.json
./lite --config config.json --test https://raw.githubusercontent.com/freefq/free/master/v2
```
![image](https://user-images.githubusercontent.com/34052608/202212027-87c3a22e-7c6a-4f6c-88f9-49c9dbf23445.png)

**Comment by ZhouG2** [comment]
你好，输出图片无法编辑复制节点，可以增加一个与linux一样的输出json文件功能么？非常感谢

**Comment by xxf098** [comment]
https://github.com/xxf098/LiteSpeedTest/releases/tag/v0.13.1
