### ISSUE TITLE
打印GooglePing、当前正在测速的节点信息（多节点测速时，进度条显示有一定的延迟，且页面容易假死）

### ISSUE THREAD

**Issue by rogerfederal** [xxf098/LiteSpeedTest#25]
1、可否打印googleping日志，便于定位准确测速进度和节点
2、大批量测速时（超1000节点，线程3，同时ping和speed）时，页面容易假死或者显示空白，但任务管理器 该进程的 内存和 CPU 却在实时的变动，并未被挂起。这样测速看控制台就清晰了，web端可以最小化以减少性能开销。
谢谢！
![image](https://github.com/rogerfederal/test/raw/main/image/20221205143653.png)

**Comment by xxf098** [comment]
1000个节点卡死是因为前端页面的table组件性能不行，需要替换掉这个table组件
大量节点建议通过命令行后台测速
