### ISSUE TITLE
v3 和 不带v3 的 区别

### ISSUE THREAD

**Issue by BlueHtml** [xxf098/LiteSpeedTest#30]
你好，releases页面，`v3`和`不带v3`的有什么区别呢？

例如：`lite-windows-amd64-v0.14.1.zip`和`lite-windows-amd64-v3-v0.14.1.zip`

**Comment by hadifarnoud** [comment]
I have the same question

**Comment by xxf098** [comment]
https://github.com/golang/go/wiki/MinimumRequirements#amd64
