### ISSUE TITLE
命令行模式能否输出可用节点到文件

### ISSUE THREAD

**Issue by 4ft35t** [xxf098/LiteSpeedTest#35]
`--test` 运行时，已经输出测速结果到 `out.png`。

能否同时把可用节点url输入到 alive.txt

**Comment by xxf098** [comment]
output as json then use [jq](https://github.com/stedolan/jq/releases) to get all the links
```bash
jq -r '.nodes[] | select(.ping!="0") |.link'  output.json
```

**Comment by 4ft35t** [comment]
默认只输出 `out.png`, 如果需要生成 josn，按以下步骤操作
1. 下载 https://raw.githubusercontent.com/xxf098/LiteSpeedTest/master/config.json
2. 把 `generatePicMode` 改成 `3`
3. `./lite --config config.json --test https://raw.githubusercontent.com/freefq/free/master/v2` 即可生成 `out.json`
